export default {
  ADD_JOKE: 'ADD_JOKE',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  BATCH_ADD: 'BATCH_ADD',
  EMPTY_JOKES: 'EMPTY_JOKES',
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  LOADING_ON: 'LOADING_ON',
  LOADING_OFF: 'LOADING_OFF',
  LOCAL_JOKES: 'LOCAL_JOKES',
  REMOVE_JOKE_BY_ID: 'REMOVE_JOKE_BY_ID',
  SELECTED_CATEGORY: 'SELECTED_CATEGORY',
  TOGGLE_FAV: 'TOGGLE_FAV',
};
