export default {
    ADD_JOKE: 'ADD_JOKE',
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    SELECTED_CATEGORY: 'SELECTED_CATEGORY',
    LOADING_ON: 'LOADING_ON',
    LOADING_OFF: 'LOADING_OFF',
    EMPTY_JOKES: 'EMPTY_JOKES',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    BATCH_ADD: 'BATCH_ADD',
    TOGGLE_FAV: 'TOGGLE_FAV',
    LOCAL_JOKES: 'LOCAL_JOKES',
};